name    'puppet-elasticsearch'
version '0.0.1'
source 'git://github.com/pdrakeweb/puppet-elasticsearch'
author 'pdrakeweb'
license 'apache'
summary 'Installs elasticsearch.'
description 'Installs elasticsearch and configures elasticsearch to run as a service.'
project_page 'https://github.com/pdrakeweb/puppet-elasticsearch'
dependency 'puppetlabs/java', '>= 0.1.5'
